### ISSUE TITLE
application/kerberos is not a registered media type

### ISSUE THREAD

**Issue by allanlw** [krb5/krb5#327]
krb5 sends a content-type: application/kerberos header in some requests. This is not an IANA registered media type.

One possible solution would be to simply change the sent content-type to be application/x-kerberos

Example: https://github.com/krb5/krb5/blob/50a3c3cbeab32577fba2b21deb72a64015c48ec7/src/lib/krb5/os/sendto_kdc.c#L558

IANA registry: http://www.iana.org/assignments/media-types/media-types.xhtml#application

**Comment by kaduk** [comment]
First off, we do not use the github issue tracker, just github pull requests -- please report bugs to krb5-bugs@mit.edu.

Second, the use of application/kerberos is for compatibility with Microsoft's implementation of the MS-KKDCP protocol.  If the "internet police" (which do not exist) were to go after anyone, that is where this media type first appeared; its use in krb5 is only for compatibility with Microsoft's proxy implementation.

**Comment by greghudson** [comment]
I'm not 100% sure that application/kerberos comes from the Microsoft implementation or is required for compatibility with it, but I have asked the contributors of that functionality for confirmation.
