### ISSUE TITLE
Cannot contact any KDC for realm

### ISSUE THREAD

**Issue by S1lks** [krb5/krb5#394]
While testing if Kerberos is correctly installed and running (`kinit administrator@DOMAIN.COM`) for my Active Directory Domain Controller with Samba 
I get error:

    kinit: Cannot contact any KDC for realm 'DOMAIN.COM' while getting initial credentials.

I traced my error with `KRB5_TRACE=/dev/stdout kinit administrator@DOMAIN.COM` and it's seems that Kerberos tries to request information from ip **10.0.2.15** but my domain is correctly configured to ip **172.20.10.50**.

Any clue what should I configure to Kerberos for requesting information from **172.20.10.50** not from **10.0.2.15**?

*resolv.conf*:

    namserserver 172.20.10.50
    search domain.com
    domain DOMAIN.COM

*interfaces*:

    auto eth0
    iface eth0 inet static
        address 172.20.10.50
        netmask 255.255.255.0
        gateway 172.20.10.1
        dns-nameservers 172.20.10.50
        dns-search domain.com

**Comment by greghudson** [comment]
We only use our github project issue tracker for pull requests.  (Unfortunately github does not allow us to turn it off independently.)  Please send your question by email to kerberos@mit.edu.
